name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Your email is 23f2003677@ds.study.iitm.ac.in
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          echo "Commit made at $(date -u)" >> daily.txt
          git add daily.txt
          git commit -m "Daily update: $(date -u)"
          git log -1

      - name: Push commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
